name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy
      - name: Check formatting (nightly)
        run: cargo +nightly fmt --all -- --check
      - name: Clippy (nightly)
        run: cargo +nightly clippy --workspace --all-targets --all-features -- -D warnings
      - name: Build (stable)
        run: cargo +stable build --workspace --all-targets --all-features --verbose
      - name: Run tests (stable)
        run: cargo +stable test --workspace --all-features --verbose
